language: php

php:
  - 5.3
  - 5.4

before_script:
  - cd ..
  - composer create-project --repository-url="http://packages.zendframework.com" zendframework/skeleton-application:dev-master
  - cd skeleton-application
  - composer require doctrine/migrations:dev-master
  - composer require sundrique/doctrine-tools:dev-master

script:
  - cd vendor/sundrique/doctrine-tools
  - phpunit
